// @generated by expo-yarn-workspaces

import 'expo/build/Expo.fx';
import registerRootComponent from 'expo/build/launch/registerRootComponent';
import { activateKeepAwakeAsync } from 'expo-keep-awake';

import App from './App';

if (__DEV__) {
  activateKeepAwakeAsync();
}

// Register the root component using Expo's preferred method
registerRootComponent(App);